### ISSUE TITLE
Add support for Firefox browser to Clear Space

### ISSUE THREAD

**Issue by Santhoshmani1** [Santhoshmani1/Clear-Space#1]
Clear Space is currently only available for the Chrome browser. adding support for the Firefox browser can benefit more users with Clear Space.

**Here are some specific tasks that need to be completed to add Firefox support:**

- Update the Clear Space manifest file to include Firefox as a supported browser.
- Implement the necessary changes to the Clear Space code to work with Firefox.

**Comment by LyubomirT** [comment]
@Santhoshmani1 Do you have a Mozilla Dev account? It will be required to compile the extension for Firefox. I can help you with preparing the .zip and the manifest, but you'll have to upload it to the website (even if private, it needs to be signed by Mozilla) to make a usable .xpi.
