### ISSUE TITLE
Subscriptions tab is removed from DOM, incorrectly assuming it as shorts tab.

### ISSUE THREAD

**Issue by Santhoshmani1** [Santhoshmani1/Clear-Space#2]
## Issue : 
**The extension's shorts tab removal feature is removing the subscriptions tab from the DOM each time when the page is reloaded.** 

### Current Behaviour
![Incorrect-Element-removed.png](https://github.com/Santhoshmani1/Clear-Space/assets/119673958/44e59ee8-b89b-4f29-b086-fe2c1853bbaf)

### Expected Behaviour
![Expected-navigation-behaviour.png](https://github.com/Santhoshmani1/Clear-Space/assets/119673958/4a61c59a-91ff-4352-aa81-d9f043cf9655)

### Solution
- In the **scripts/main.js** file, Add conditional checking to confirm that element will be shorts Tab from the Youtube DOM.
- Specifying Aria-label / title  to the ```navItems[1]``` will solve the bug.

**Comment by pbelokon** [comment]
@Santhoshmani1 I want to give this a try
