### ISSUE TITLE
Firefox Build Archive

### ISSUE THREAD

**Issue by LyubomirT** [Santhoshmani1/Clear-Space#8]
This is related to #7 and #1. Here you can find the `.zip` file that needs to be uploaded to the Mozilla Dev Panel and then converted into an `.xpi` file which can be used for Firefox.

[cspace-for-firefox.zip](https://github.com/Santhoshmani1/Clear-Space/files/13997371/cspace-for-firefox.zip)

**Comment by Santhoshmani1** [comment]
Thank you for the contribution @LyubomirT .
